FROM node:16-alpine
WORKDIR /usr/app

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/app/node_modules/.bin:$PATH

WORKDIR /usr/app/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

CMD ["ls"]
CMD ["npm", "run", "start:watch"]